// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AgreementInfo struct {
	Index         int    `json:"index"`
	Creator       string `json:"creator"`
	Name          string `json:"name"`
	CreateAt      string `json:"create_at"`
	Status        int    `json:"status"`
	Signers       string `json:"signers"`
	AgreementFile string `json:"agreement_file"`
	SignInfos     string `json:"sign_infos"`
	Resources     string `json:"resources"`
}

type Filter struct {
	Creator string `json:"creator"`
	Signer  string `json:"signer"`
	Status  []int  `json:"status"`
}

type NewAgreementInfo struct {
	Index         int    `json:"index"`
	Creator       string `json:"creator"`
	Name          string `json:"name"`
	CreateAt      string `json:"create_at"`
	Status        int    `json:"status"`
	Signers       string `json:"signers"`
	AgreementFile string `json:"agreement_file"`
	SignInfos     string `json:"sign_infos"`
	Resources     string `json:"resources"`
}

type PagingParam struct {
	Page      int    `json:"page"`
	Size      int    `json:"size"`
	SortField string `json:"sortField"`
	Order     string `json:"order"`
}

type PagingResult struct {
	Page  int              `json:"page"`
	Size  int              `json:"size"`
	Total int              `json:"total"`
	Data  []*AgreementInfo `json:"data"`
}
